services:
  - type: web
    name: flask-api
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    branch: main
    autoDeploy: true
